/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1s22015_201212596;

import practica1s22015_201212596.clases.Nodoobjetos_201212596;
import practica1s22015_201212596.clases.Lista_objetos_201212596;
import java.io.File;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author danielvega
 */
public class pantobjetos_201212596 extends javax.swing.JFrame {
int indice = 0;
int tamaño = 1;
String ruta;

Lista_objetos_201212596 personajes = new Lista_objetos_201212596();
Nodoobjetos_201212596 nodo;
       
    /**
     * Creates new form pantobjetos_201212596
     */
    public pantobjetos_201212596() {
        initComponents();
        
        
        
               
    }
    
    public void cargarimagenes(){
           try {
            JFileChooser abrir = new JFileChooser();
            abrir.setFileSelectionMode(JFileChooser.FILES_ONLY);

            int seleccion = abrir.showOpenDialog(this);

            if (seleccion == JFileChooser.APPROVE_OPTION) {
                File f = abrir.getSelectedFile();
                try {
                    lblimagen.setText("");
                    String path = f.getAbsolutePath();
                    //String path = lblmario.get
                    ruta=path;
                    ImageIcon icon = new ImageIcon(path);
                    lblimagen.setIcon(icon);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane,"Error adentro de segundo try");
                }
            }

        } catch (Exception e) {JOptionPane.showMessageDialog(rootPane,"Error al abrir archivo");
        }     
           }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnombrepersonaje = new javax.swing.JTextField();
        lblimagen = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rbtnpila = new javax.swing.JRadioButton();
        rbtncola = new javax.swing.JRadioButton();
        btnterminar = new javax.swing.JButton();
        btnbowser = new javax.swing.JButton();
        btnmario = new javax.swing.JButton();
        btnkoopita = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblimagen.setText("Imagen");
        lblimagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimagenMouseClicked(evt);
            }
        });

        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de Objeto");

        rbtnpila.setText("Pila");

        rbtncola.setText("Cola");

        btnterminar.setText("Terminar");
        btnterminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnterminarActionPerformed(evt);
            }
        });

        btnbowser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1s22015_201212596/imagenes/bowser.png"))); // NOI18N

        btnmario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1s22015_201212596/imagenes/mario.png"))); // NOI18N

        btnkoopita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1s22015_201212596/imagenes/koopitas.png"))); // NOI18N

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbowser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombrepersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(btnagregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnpila)
                            .addComponent(rbtncola, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnterminar)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnmario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnkoopita)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButton4)
                .addGap(30, 30, 30)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnpila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtncola))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(6, 6, 6)
                            .addComponent(txtnombrepersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnagregar))
                        .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnterminar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbowser)
                    .addComponent(btnmario)
                    .addComponent(btnkoopita))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        int correlativo = 0;   
        try
        {
            Nodoobjetos_201212596 aux = personajes.ultimo;
            personajes.insertarnodo(ruta, txtnombrepersonaje.getText(),correlativo);
            JOptionPane.showMessageDialog(rootPane, "Se agrego un nuevo dato a la Lista de Objetos");
           /** Form_editar_planta Fep=new Form_editar_planta();
            Fep.setVisible(true);
            Fep.plantas(Plantas, Ljugador);**/
            correlativo += 1;
            
                    
         }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error al insertar un nuevo dato");
        }
           personajes.Imprimir();
       
    }//GEN-LAST:event_btnagregarActionPerformed

    private void lblimagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimagenMouseClicked
        cargarimagenes();
        lblimagen.repaint();
        this.repaint();
    }//GEN-LAST:event_lblimagenMouseClicked

    private void btnterminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnterminarActionPerformed
        // TODO add your handling code here:
        pantallacrearjuego_201212596 pant = new pantallacrearjuego_201212596();
        pant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnterminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantobjetos_201212596.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantobjetos_201212596.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantobjetos_201212596.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantobjetos_201212596.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantobjetos_201212596().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbowser;
    private javax.swing.JButton btnkoopita;
    private javax.swing.JButton btnmario;
    private javax.swing.JButton btnterminar;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JRadioButton rbtncola;
    private javax.swing.JRadioButton rbtnpila;
    private javax.swing.JTextField txtnombrepersonaje;
    // End of variables declaration//GEN-END:variables
}
