/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1s22015_201212596;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author danielvega
 */
public class pantobjetos_201212596 extends javax.swing.JFrame {
int indice = 0;
    /**
     * Creates new form pantobjetos_201212596
     */
    public pantobjetos_201212596() {
        initComponents();
        
        
        
               
    }
    
    public void cargarimagenes(){
    switch(indice) {
            case 0:
                String path = "/practica1s22015_201212596/mario.png";
                URL url = this.getClass().getResource(path);
                ImageIcon icon = new ImageIcon(url);
                lblimagen.setIcon(icon);
                break;
            case 1:
                String path1 = "/practica1s22015_201212596/koopitas.png";
                URL url1 = this.getClass().getResource(path1);
                ImageIcon icon1 = new ImageIcon(url1);
                lblimagen.setIcon(icon1);
                break;
             case 2:
                String path2 = "/practica1s22015_201212596/goomba.png";
                URL url2 = this.getClass().getResource(path2);
                ImageIcon icon2 = new ImageIcon(url2);
                lblimagen.setIcon(icon2);
                break;
            default:

                break;
        }

    
    
    
    }
    
    public void insertarnodo(){
        Nodo_201212596 cabeza = new Nodo_201212596();
        Nodo_201212596 nuevo = new Nodo_201212596();
        Nodo_201212596 aux = new Nodo_201212596();
        
        aux = cabeza;
        nuevo.setNombre(txtnombrepersonaje.getText());
        nuevo.setImagen(lblimagen.getIcon());
        
        
         if (cabeza == null) {   // preguntamos si cabeza es null si lo es eso significa que la lista esta vacia 
            cabeza = nuevo; // asignamos cabeza como nuevo
            cabeza.sig = null; // indicamos que el siguiente de cabeza es null

        } 
         else {  
            do {
                if (aux.sig == null) { // pregunto si ya llego al final de lista
                    aux.sig = nuevo;   // le asigno el siguiente del nodo aux a nuevo
                    nuevo.sig = null;  // indicamos que el siguiente de nuevo es nulo
          } 
           aux= aux.sig;  // decimos que aux va ser igual a el siguiente de el mismo.
        }while(aux!=null);   // el while se va repetir mientras aux no sea igual a nulo
    }
        
       
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnizquierda = new javax.swing.JButton();
        btnderecha = new javax.swing.JButton();
        txtnombrepersonaje = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        lblimagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnizquierda.setText("Izquierda");
        btnizquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnizquierdaActionPerformed(evt);
            }
        });

        btnderecha.setText("Derecha");
        btnderecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnderechaActionPerformed(evt);
            }
        });

        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnizquierda)
                .addGap(38, 38, 38)
                .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnderecha))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnombrepersonaje)
                    .addComponent(btnagregar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnizquierda)
                            .addComponent(btnderecha)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtnombrepersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnagregar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnderechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnderechaActionPerformed
       
        if(indice == 2){
           indice = 0;        
              System.out.println(indice);
           cargarimagenes();
           }  
       else{
           indice = indice + 1;   
           System.out.println(indice);
           cargarimagenes();
              
           }  
    }//GEN-LAST:event_btnderechaActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
     
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnizquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnizquierdaActionPerformed
      
        if(indice == 0){
           indice = 2;  
           System.out.println(indice);
            cargarimagenes();
           }  
       else{
           indice = indice - 1;  
           System.out.println(indice);
            cargarimagenes();
           }  
       
    }//GEN-LAST:event_btnizquierdaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantobjetos_201212596.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantobjetos_201212596.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantobjetos_201212596.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantobjetos_201212596.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantobjetos_201212596().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnderecha;
    private javax.swing.JButton btnizquierda;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JTextField txtnombrepersonaje;
    // End of variables declaration//GEN-END:variables
}
